language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -U pip
  - pip install --only-binary=numpy,scipy,statsmodels numpy scipy statsmodels
  - pip install -r requirements.txt
# command to run tests
script: tox --sitepackages
