language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -U pip
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
  - pip uninstall --yes tensorflow
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp27-none-linux_x86_64.whl
# command to run tests
script:
  - rm DSTK/tests/tests_gam/test_p_spline_train.py
  - tox --sitepackages
