language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -U pip
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r linux.txt
  - python setup.py develop
# command to run tests
script:
  - rm DSTK/tests/tests_gam/test_p_spline_train.py
  - rm DSTK/tests/test_constrained_logit/test_constrained_logit.py
  - tox --sitepackages
