language: python
python:
  - "2.7"
sudo: required
dist: trusty
# command to install dependencies
install:
  - pip install -U pip
  - pip install --only-binary=numpy,scipy
  - pip install -r requirements.txt
# command to run tests
script: tox --sitepackages
